### ISSUE TITLE
Add baseline method to RTP

### ISSUE THREAD

**Issue by emdupre** [rmarkello/rtpeaks#4]
Baseline method needs to be added to RTP class for better instantiation of peak finding variables.

**Comment by rmarkello** [comment]
This has been largely resolved as of https://github.com/rmarkello/rtpeaks/commit/f7777216cfc649785618b62fe67fc3337b3af36b. You can call RTP.start_baseline() and RTP.stop_baseline() prior to peak finding to improve accuracy. Because of these recent changes it is highly recommended that an RTP instance be baselined before proceeding with peak finding.
